# Generated by Django 2.0 on 2019-01-26 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20181216_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='active_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='код подтверждения'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 16, 4, 22, 972443, tzinfo=utc)),
        ),
    ]
